apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    name: pod-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
      - mountPath: /container-volume
        name: primeiro-volume
  - name: jenkins-container
    image: jenkins:alpine
    volumeMounts:
      - mountPath: /container-volume
        name: primeiro-volume
  volumes:
  - name: primeiro-volume
    hostPath:
      path: /C/volumes
      type: Directory